package com.monkeycoding.xyz.entity;

public class Article {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.id
     *
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_tags
     *
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    private String articleTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.group_id
     *
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.created
     *
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    private Long created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.modifyed
     *
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    private Long modifyed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    private String articleContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.id
     *
     * @return the value of article.id
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.id
     *
     * @param id the value for article.id
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_tags
     *
     * @return the value of article.article_tags
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public String getArticleTags() {
        return articleTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_tags
     *
     * @param articleTags the value for article.article_tags
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public void setArticleTags(String articleTags) {
        this.articleTags = articleTags == null ? null : articleTags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.group_id
     *
     * @return the value of article.group_id
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.group_id
     *
     * @param groupId the value for article.group_id
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.created
     *
     * @return the value of article.created
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.created
     *
     * @param created the value for article.created
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public void setCreated(Long created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.modifyed
     *
     * @return the value of article.modifyed
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public Long getModifyed() {
        return modifyed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.modifyed
     *
     * @param modifyed the value for article.modifyed
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public void setModifyed(Long modifyed) {
        this.modifyed = modifyed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     * @mbggenerated Sat Jan 23 13:00:32 CST 2016
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }
}