package com.monkeycoding.xyz.entity;

public class TaskFactor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_factor.id
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_factor.item_id
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_factor.attr
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    private String attr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_factor.created
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    private Long created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_factor.id
     *
     * @return the value of task_factor.id
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_factor.id
     *
     * @param id the value for task_factor.id
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_factor.item_id
     *
     * @return the value of task_factor.item_id
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_factor.item_id
     *
     * @param itemId the value for task_factor.item_id
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_factor.attr
     *
     * @return the value of task_factor.attr
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public String getAttr() {
        return attr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_factor.attr
     *
     * @param attr the value for task_factor.attr
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public void setAttr(String attr) {
        this.attr = attr == null ? null : attr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_factor.created
     *
     * @return the value of task_factor.created
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_factor.created
     *
     * @param created the value for task_factor.created
     *
     * @mbggenerated Sat Jan 23 13:14:51 CST 2016
     */
    public void setCreated(Long created) {
        this.created = created;
    }
}