package com.monkeycoding.xyz.entity;

public class TaskItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item.id
     *
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item.task_id
     *
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    private Task task;

    public Task getTask() {
        return task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item.request_url
     *
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    private String requestUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_item.created
     *
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    private Long created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item.id
     *
     * @return the value of task_item.id
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item.id
     *
     * @param id the value for task_item.id
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item.request_url
     *
     * @return the value of task_item.request_url
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    public String getRequestUrl() {
        return requestUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item.request_url
     *
     * @param requestUrl the value for task_item.request_url
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    public void setRequestUrl(String requestUrl) {
        this.requestUrl = requestUrl == null ? null : requestUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_item.created
     *
     * @return the value of task_item.created
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    public Long getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_item.created
     *
     * @param created the value for task_item.created
     * @mbggenerated Sat Jan 23 13:13:47 CST 2016
     */
    public void setCreated(Long created) {
        this.created = created;
    }
}