package com.monkeycoding.xyz.mapper;

import com.monkeycoding.xyz.entity.Task;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Repository("taskMapper")
@Component
public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sat Jan 23 13:12:47 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sat Jan 23 13:12:47 CST 2016
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sat Jan 23 13:12:47 CST 2016
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sat Jan 23 13:12:47 CST 2016
     */
    Task selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sat Jan 23 13:12:47 CST 2016
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbggenerated Sat Jan 23 13:12:47 CST 2016
     */
    int updateByPrimaryKey(Task record);
}